name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      JAR_NAME: JJBA-RipplesOfThePast-1.16.5
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run build with Gradle Wrapper
        run: |
          ./gradlew build
          ls build/libs
      # Get Tag For Release
      - name: Get Tag
        id: get_tag
        env:
          REF: ${{ github.ref }} # e.g. refs/tags/v1.0.0
        run: |
          TAG=${REF/refs\/tags\/v}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          # mv build/libs/${{ env.JAR_NAME}}-*.jar build/libs/${{ env.JAR_NAME}}-${TAG}.jar 
      # Publish Release
      - name: Publish Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          TAG: ${{ steps.get_tag.outputs.tag }} # 获取上一步截取到的版本号，既 1.0.0
        with:
          name: Build ${{ env.TAG }}
          body: Build ${{ env.TAG }} Release.
          files: build/libs/${{ env.JAR_NAME}}-${{ env.TAG }}.jar